### Import Numpy

In [ ]:
import numpy
import numpy as np

### Mengecek versi Numpy

In [ ]:
print(np.__version__)

1.21.6


In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
# !pip --version
# !pip show numpy
# !pip install numpy==1.20

### Membuat Numpy Array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# Python List

a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

type(a), type(b)

(list, list)

In [ ]:
print(a + b)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
print(a * b)

TypeError: ignored

In [ ]:
arrayA = np.array(a)
arrayB = np.array(b)

type(arrayA), type(arrayB)

(numpy.ndarray, numpy.ndarray)

In [ ]:
print(arrayA + arrayB)
print(arrayA / arrayB)

[ 6  8 10 12]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
print(arrayA * 10) # broadcasting

[10 20 30 40]


In [ ]:
y_pred = np.array([1, 0, 0, 1, 1, 0, 1, 1])
labels = np.array([0, 1, 0, 1, 1, 0, 1, 1])

mse = (1/len(labels)) * np.sum(np.square(y_pred - labels))
print(mse)

0.25


### Membuat Numpy Array 0 Dimensi (0D)

In [ ]:
arr = np.array(42)

print(arr)

42


### Membuat Numpy Array 1 Dimensi (1D)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### Membuat Numpy Array 2 Dimensi (2D)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### Membuat Numpy Array 3 Dimensi (3D)

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Membuat Numpy Array 0s dan 1s

In [ ]:
arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:
arr = np.zeros((5, 2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
arr = np.ones((7, 7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
arr = np.ones((3, 4, 2))
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


### Menghapus Array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr = np.delete(arr, 1, axis=0)
print(arr)

[[1 2 3]
 [7 8 9]]


In [ ]:
del arr

### Mengakses Elemen Pada Numpy Array 1D

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


### Mengakses Elemen Pada Numpy Array 2D

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, 4])

10


### Mengakses Elemen Pada Numpy Array 2D

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[1, 2, 3], [4, 5, 6]]])

print(arr[0, 1, 2])

6


### Mengakses Numpy Array dengan indeks negatif

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, -1])

10


### Mengakses Elemen Sekaligus Pada Numpy Array

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


### Mengecek Tipe Data Pada Numpy Array

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


### Mendefinisikan Tipe Data Pada Numpy Array

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='I')

print(arr)
print(arr.dtype)

[1 2 3 4]
uint32


In [ ]:
arr = np.array([1, 2, 3, 4], dtype=np.int16)

print(arr)
print(arr.dtype)

[1 2 3 4]
int16


### Mengubah Tipe Data Pada Numpy Array

In [ ]:
arr = np.array([1.1, 2.1, 3.1])
arr = arr.astype('i')

print(arr)
print(arr.dtype)

[1 2 3]
int32


### Fungsi Arange

In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
arr = np.arange(10, 20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
arr = np.arange(10, 20, 2) # arguments: start, stop, step
print(arr)

[10 12 14 16 18]


In [ ]:
arr = np.arange(-1, 1, 0.1)
print(arr)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


### Mendapatkan shape dari Array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
print(arr.size)

8


In [ ]:
print(arr.ndim)

2


### Menggunakan ndmin untuk mendefinisikan dimensi

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr.shape)

(1, 1, 1, 1, 4)


### Reshape dari 1D ke 2D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(4, 3)

print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape dari 1D ke 3D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr = arr.reshape(2, 3, 2)

print(arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Menggunakan -1 pada proses reshaping

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr= arr.reshape(2, 2, -1)

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Melakukan flattening pada Array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr= arr.reshape(-1)

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr= arr.flatten()

print(arr)

[1 2 3 4 5 6]


### Melakukan duplikasi pada Array menggunakan copy()

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr, x)

[42  2  3  4  5] [1 2 3 4 5]


### Melakukan duplikasi pada Array menggunakan view()

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr, x)

[42  2  3  4  5] [42  2  3  4  5]


---

### Iterasi pada Numpy Arrray 1D

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


### Iterasi pada Numpy Arrray 2D

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


### Iterasi pada Numpy Arrray 3D

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### Iterasi dengan nditer()

In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


### Iterasi dengan ndenumerate() pada Array 1D

In [ ]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


### Iterasi dengan ndenumerate() pada Array 2D

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Join terhadap 2 Array 1D

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Join terhadap 2 Array 2D

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### Stack terhadap 2 Array 1D

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Stack terhadap 2 Array 1D menggunakan hstack()

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


### Stack terhadap 2 Array 1D menggunakan vstack()

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


### Split terhadap 1 Array 1D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr = np.array_split(arr, 4)

print(arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Split terhadap 1 Array 2D

In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6],
                [7, 8], [9, 10], [11, 12]])
arr = np.array_split(arr, 3)

print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6],
                [7, 8], [9, 10], [11, 12]])
arr = np.array_split(arr, 3, axis=1)

print(arr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int64)]


### Search pada Array 1D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr**2 == 4)

print(x)

(array([1]),)


### Sort pada Array 1D

In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array(['pisang', 'melon', 'apel'])

print(np.sort(arr))

['apel' 'melon' 'pisang']


### Sort pada Array 2D

In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### Filter pada Numpy Array 1D

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
arr = arr[x]

print(arr)

[41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
arr = arr[filter_arr]

print(arr)

[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
arr = arr[filter_arr]

print(arr)

[2 4 6]


---

### Filter pada Numpy Array 1D menggunakan lebih dari 1 kondisi

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = (arr % 2 == 0) & (arr > 2)
arr = arr[filter_arr]

print(arr)

[4 6]


### Filter pada Numpy Array 2D

In [ ]:
arr = np.array([['1', 'one'],
                ['2', 'two'],
                ['3', 'three'],
                ['4', 'four'],
                ['5', 'five']])

filter = np.array(['two', 'four'])
arr = arr[np.in1d(arr[:, 1], filter)]

print(arr)

[['2' 'two']
 ['4' 'four']]


### Mendapatkan nilai integer secara random

In [ ]:
from numpy import random

x = random.randint(100)

print(x)

22


### Mendapatkan nilai float secara random

In [ ]:
x = random.rand()

print(x)

0.33553885090365543


### Membuat Array 1D dengan nilai integer secara Random

In [ ]:
x = random.randint(100, size=(5))

print(x)

[ 5 58 63 35 75]


### Membuat Array 2D dengan nilai integer secara Random

In [ ]:
x = random.randint(100, size=(3, 5))

print(x)

[[31 79 31 56 18]
 [80 21 50 31 18]
 [63 18 59 28  3]]


### Membuat Array 1D dengan nilai float secara Random

In [ ]:
x = random.rand(5)

print(x)

[0.33158433 0.40869198 0.7893277  0.70715339 0.36104075]


### Membuat Array 2D dengan nilai float secara Random

In [ ]:
x = random.rand(3, 5)

print(x)

[[0.17154852 0.24903471 0.31508807 0.09304131 0.9576493 ]
 [0.5122721  0.84050068 0.24508325 0.00696401 0.79633127]
 [0.38470687 0.47702144 0.86665335 0.01258899 0.91271168]]


### Membuat nilai integer random dari Array 1D

In [ ]:
x = random.choice([3, 5, 7, 9])

print(x)

3


### Mengacak nilai yang ada pada Array 1D

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)

print(arr)

[5 1 4 3 2]


---

---

---

---